name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your simulator code, full history (needed for gh-pages)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Set up Node.js
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3) Install & build
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build    # outputs into ./dist

      # 4) Deploy ./dist to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
